name: rcolinkennedy
favicon: null
layout_spectrum: 0.03293383866548538
typography_spectrum: 0.8997041918337345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6718087734188884
  lightness: 0.7781863661948591
  saturation: 0.824008371680975
  rhythmicContrast: 0.02652668673545122
purpose: []
